### ISSUE TITLE
🚀Populate Document Tables from XML 

### ISSUE THREAD

**Issue by thekaushikls** [dotVSON/GhXmlParser#3]
# DESCRIPTION

To represent the Grasshopper file in the `.VSON` format, various elements need to be extracted from the `.GHX` file and stored in the below attributes of the [`VSON.Core.Document`](https://github.com/dotVSON/VSON.Core/blob/develop/VSON.Core/Document.cs) instance.
1. [ComponentTable](https://github.com/dotVSON/VSON.Core/blob/develop/VSON.Core/Document.cs#L25)
2. [ParameterTable](https://github.com/dotVSON/VSON.Core/blob/develop/VSON.Core/Document.cs#L23)
3. [WireTable](https://github.com/dotVSON/VSON.Core/blob/develop/VSON.Core/Document.cs#L24)

---
<br>

### TASKS
- [ ] 🚀 Generate list of Components in file
- [ ] 🚀 Generate list of I/O Parameters in file
- [ ] 🚀 Generate list of Standalone Parameters in file
- [ ] 🚀 Generate list of Wires connecting I/O Parameters in file
